### ISSUE TITLE
"Crash" due to Plague

### ISSUE THREAD

**Issue by Biochao** [Sunconure11/HistoricizedMedicine#10]
The effects of Plague seem to cause an integrated server crash on singleplayer. Once the plague has been transferred to other entities all ticks seem to halt and a force quit is required to close the game. No crash report generated.

How to reproduce:

- Created a pack of just Historicized Medicine 1.3.8 and JEI
- New World
- Spawn a bunch of rats
- Spawn a bunch of cows
- wait

My client log:[latest.log](https://github.com/Sunconure11/HistoricizedMedicine/files/2555722/latest.log)

**Comment by Sunconure11** [comment]
Uh, you sure this is the right log? I'm having a hard time finding your crash in the log.

**Comment by Biochao** [comment]
There was no crash report generated. The integrated sever just froze and I had to force quit the game. It’s strange as I was still able to move around the world and the day night cycle appeared to continue, but I couldn’t interact with any entity or run any commands.

**Comment by Sunconure11** [comment]
I've noted that server consoles can freeze in general, regardless of what mods are in. Just interact with the console from time to time to stop this. If you can prove this is connected to this mod, I will reopen it.
