### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by coolnickname** [Sunconure11/HistoricizedMedicine#16]
https://pastebin.com/raw/gCUyy98L

Happens on SpongeForge. The issue seems to be the overriding of `final method getId` in `ItemBase`.

**Comment by Sunconure11** [comment]
I’ll try some stuff. This mod is in maintenance mode at this point. Sorry about the very late reply, I didn’t see this at all.

**Comment by Rutes** [comment]
Hey there I just found your mod and wanted to add it to my modpack to show kids different kinds of scientific discoveries. Unfortunately, I am also experiencing this error with SpongeForge on my server.

Here are my logs in case they can be helpful: 
latest.log
https://pastebin.com/ETJQsDt4
debug.log
https://pastebin.com/7Mvd8bp6

**Comment by Sunconure11** [comment]
Yeah, I'm pretty sure I know what's causing this, but I have been working on two other projects.

**Comment by Sunconure11** [comment]
Sorry, but read this. Updating mixin on Forge wont really work out here well. This provides another solution instead.

https://github.com/Um-Mitternacht/Bewitchment/issues/527#issuecomment-598124428
