### ISSUE TITLE
Oddball crash on superflat worlds

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/HistoricizedMedicine#4]
https://paste.dimdev.org/ujikabebic.mccrash

Probably incredibly rare, but it warrants more investigation.

**Comment by Sunconure11** [comment]
Due to the rarity of it, it is not a high priority, but if others start encountering it, further investigation will be done.

**Comment by vaIgarashi** [comment]
Looks like random not initialized. This may be due using constructor w/o args

**Comment by Sunconure11** [comment]
Since I'm legitimately unsure as to what caused this crash, and I've only encountered it once, if you know how to fix it, feel free to shoot a pull request @ensirius, and I'll push out an update to the mod.

**Comment by Sunconure11** [comment]
Aberrant error showed itself once more. Due to an inbound hurricane, I'll let you see if you want to push a pull @ensirius.

https://paste.dimdev.org/xakoyapehe.mccrash

**Comment by vaIgarashi** [comment]
I am sorry, but i can't help you. I hate to setup any forge mode

**Comment by Sunconure11** [comment]
Issue seems to be striking me more frequently. Will push out a bugfix within the next few days once I know what is going wrong.

Faulty lines have been identified, I just need to figure out how to fix them.

https://pastebin.com/ZaGik1FP

**Comment by Sunconure11** [comment]
This crash has not shown itself as of yet. I will consider it closed for now.
